INFO     HTTP_LOGGER:event_hooks.py:25 Make POST request to http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:33 Got response 200 OK from http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:25 Make POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:33 Got response 200 OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:25 Make POST request to http://localhost:8000/api/v1/files
INFO     HTTP_LOGGER:event_hooks.py:33 Got response 200 OK from http://localhost:8000/api/v1/files
INFO     HTTP_LOGGER:event_hooks.py:25 Make GET request to http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP_LOGGER:event_hooks.py:33 Got response 422 Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:17 Chek that response status code equals to 422
INFO     FILES_ASSERTIONS:files.py:125 Check get file with incorrect file id response
INFO     COURSES_ASSERTIONS:errors.py:39 Check validation error response
INFO     BASE_ASSERTIONS:base.py:69 Chek that length of "details" equals to "1"
INFO     COURSES_ASSERTIONS:errors.py:18 Check validation error
INFO     BASE_ASSERTIONS:base.py:35 Chek that "type" equals to "uuid_parsing"
INFO     BASE_ASSERTIONS:base.py:35 Chek that "input" equals to "incorrect-file-id"
INFO     BASE_ASSERTIONS:base.py:35 Chek that "context" equals to "{'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}"
INFO     BASE_ASSERTIONS:base.py:35 Chek that "message" equals to "Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1"
INFO     BASE_ASSERTIONS:base.py:35 Chek that "location" equals to "['path', 'file_id']"
INFO     SCHEMA_ASSERTIONS:schema.py:19 Validate JSON schema